language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly

sudo: false

services:
    - mysql

before_install:
    - composer require satooshi/php-coveralls:1.*
    - travis_retry composer install --dev --no-interaction

before_script:
    - cp test-config.yml.travis test-config.yml

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_script: php vendor/bin/coveralls -v
