language: php

php:
    - '5.6'

env:
    - VIRTUOSO=7.1.0

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache
        - virtuoso-opensource

dist: trusty
sudo: required

services:
    - mysql

before_install:
    - bash ./scripts/travis/install-extensions.sh
    - bash ./scripts/travis/install-services.sh
    - composer require satooshi/php-coveralls:1.*
    - travis_retry composer install --dev --no-interaction

before_script:
    - cp test-config.yml.travis test-config.yml
    - sed -i 's|<[/]\?log[^>]*>||' phpunit.xml

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_script: php vendor/bin/coveralls -v
