language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

sudo: false

install:
  - travis_retry composer install --no-interaction

before_script:
  - cp test-config.yml.dist test-config.yml

script: vendor/bin/phpunit
