language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

env:
    - VIRTUOSO=6.1.7
    - VIRTUOSO=7.1.0
    - VIRTUOSO=7.2.4.2

matrix:
    fast_finish: true
    include:
        - php: hhvm
        - php: '5.4'
          env: VIRTUOSO=6.1.4
        - php: '5.4'
          env: VIRTUOSO=6.1.6
        - php: '5.4'
          env: VIRTUOSO=7.2.0
    allow_failures:
        - env: VIRTUOSO=6.1.4
        - env: VIRTUOSO=6.1.6
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache
        - virtuoso-opensource

sudo: true

services:
    - mysql

before_install:
    - bash ./scripts/travis/install-extensions.sh
    - bash ./scripts/travis/install-services.sh
    - composer require satooshi/php-coveralls:1.*
    - travis_retry composer install --dev --no-interaction

script: bash ./scripts/run-tests.sh

after_script: php vendor/bin/coveralls -v
